"""make note_id unique key

Revision ID: 019d53fbe3ed
Revises: ecc4d88d9a61
Create Date: 2025-09-03 16:46:47.861879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '019d53fbe3ed'
down_revision: Union[str, Sequence[str], None] = 'ecc4d88d9a61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'visits', ['note_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visits', type_='unique')
    # ### end Alembic commands ###
