"""add uploaded_by and uploaded_at to visits

Revision ID: 0c1f6e6196fd
Revises: fffdc6ef10e5
Create Date: 2025-09-02 19:01:20.552218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c1f6e6196fd'
down_revision: Union[str, Sequence[str], None] = 'fffdc6ef10e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('uploaded_by', sa.Integer(), nullable=True))
    op.add_column('visits', sa.Column('uploaded_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key(None, 'visits', 'users', ['uploaded_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visits', type_='foreignkey')
    op.drop_column('visits', 'uploaded_at')
    op.drop_column('visits', 'uploaded_by')
    # ### end Alembic commands ###
