"""addColumn noteNumber

Revision ID: 32cea4f2749c
Revises: b5abfa52de61
Create Date: 2025-09-11 18:09:23.240790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32cea4f2749c'
down_revision: Union[str, Sequence[str], None] = 'b5abfa52de61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('note_number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visits', 'note_number')
    # ### end Alembic commands ###
