"""create row visituid

Revision ID: 54767f4b64b1
Revises: fa7b56d1b7ac
Create Date: 2025-09-11 14:28:28.698787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54767f4b64b1'
down_revision: Union[str, Sequence[str], None] = 'fa7b56d1b7ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('visit_uid', sa.UUID(), nullable=True, comment='Stable visit identifier across related notes (not unique, reused)'))
    op.create_index(op.f('ix_visits_visit_uid'), 'visits', ['visit_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visits_visit_uid'), table_name='visits')
    op.drop_column('visits', 'visit_uid')
    # ### end Alembic commands ###
