"""change visituid to str

Revision ID: b5abfa52de61
Revises: 54767f4b64b1
Create Date: 2025-09-11 14:52:29.528473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5abfa52de61'
down_revision: Union[str, Sequence[str], None] = '54767f4b64b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visits', 'visit_uid',
               existing_type=sa.UUID(),
               type_=sa.String(length=20),
               nullable=True,
               existing_comment='Stable visit identifier across related notes (not unique, reused)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visits', 'visit_uid',
               existing_type=sa.String(length=20),
               type_=sa.UUID(),
               nullable=True,
               existing_comment='Stable visit identifier across related notes (not unique, reused)')
    # ### end Alembic commands ###
