"""create visits table

Revision ID: c55ec56baf20
Revises: 
Create Date: 2025-08-28 17:34:38.705132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c55ec56baf20'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.BigInteger(), nullable=True),
    sa.Column('patient_id', sa.BigInteger(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('case_description', sa.String(length=255), nullable=True),
    sa.Column('case_date', sa.Date(), nullable=True),
    sa.Column('primary_ins_id', sa.String(length=50), nullable=True),
    sa.Column('primary_insurance', sa.String(length=100), nullable=True),
    sa.Column('secondary_ins_id', sa.String(length=50), nullable=True),
    sa.Column('secondary_insurance', sa.String(length=100), nullable=True),
    sa.Column('note_date', sa.Date(), nullable=True),
    sa.Column('referring_provider', sa.String(length=150), nullable=True),
    sa.Column('ref_provider_npi', sa.String(length=20), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('finalized_date', sa.Date(), nullable=True),
    sa.Column('pos', sa.String(length=20), nullable=True),
    sa.Column('visit_type', sa.String(length=100), nullable=True),
    sa.Column('attendance', sa.String(length=50), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('supervisingTherapist', sa.String(length=150), nullable=True),
    sa.Column('visitingTherapist', sa.String(length=150), nullable=True),
    sa.Column('cpt_code', sa.String(length=50), nullable=True),
    sa.Column('total_units', sa.Integer(), nullable=True),
    sa.Column('date_billed', sa.Date(), nullable=True),
    sa.Column('billed_comment', sa.Text(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('case_type', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('hold', sa.Boolean(), nullable=False),
    sa.Column('billed', sa.Boolean(), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('auth_number', sa.String(length=50), nullable=True),
    sa.Column('medical_record_no', sa.String(length=50), nullable=True),
    sa.Column('medical_diagnosis', sa.Text(), nullable=True),
    sa.Column('rendering_provider_npi', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visits_id'), 'visits', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visits_id'), table_name='visits')
    op.drop_table('visits')
    # ### end Alembic commands ###
