"""change column name from camel to underscore

Revision ID: ecc4d88d9a61
Revises: 0c1f6e6196fd
Create Date: 2025-09-03 16:11:10.001737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecc4d88d9a61'
down_revision: Union[str, Sequence[str], None] = '0c1f6e6196fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('supervising_therapist', sa.String(length=150), nullable=True))
    op.add_column('visits', sa.Column('visiting_therapist', sa.String(length=150), nullable=True))
    op.drop_column('visits', 'supervisingTherapist')
    op.drop_column('visits', 'visitingTherapist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('visitingTherapist', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('visits', sa.Column('supervisingTherapist', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_column('visits', 'visiting_therapist')
    op.drop_column('visits', 'supervising_therapist')
    # ### end Alembic commands ###
