"""add visit.columns review

Revision ID: fa7b56d1b7ac
Revises: 019d53fbe3ed
Create Date: 2025-09-03 19:41:50.643032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa7b56d1b7ac'
down_revision: Union[str, Sequence[str], None] = '019d53fbe3ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('review_needed', sa.Boolean(), nullable=False))
    op.add_column('visits', sa.Column('review_reason', sa.Text(), nullable=True))
    op.add_column('visits', sa.Column('review_by', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'visits', 'users', ['review_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visits', type_='foreignkey')
    op.drop_column('visits', 'review_by')
    op.drop_column('visits', 'review_reason')
    op.drop_column('visits', 'review_needed')
    # ### end Alembic commands ###
