"""create registrationToken table

Revision ID: fffdc6ef10e5
Revises: 383a6537a217
Create Date: 2025-09-02 15:41:48.212143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fffdc6ef10e5'
down_revision: Union[str, Sequence[str], None] = '383a6537a217'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_tokens_id'), 'registration_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_registration_tokens_token'), 'registration_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registration_tokens_token'), table_name='registration_tokens')
    op.drop_index(op.f('ix_registration_tokens_id'), table_name='registration_tokens')
    op.drop_table('registration_tokens')
    # ### end Alembic commands ###
